name: Check Datasets Directory

on:
  push:
    branches:
      - main
jobs:
  check-files-and-directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if datasets directory exists
        run: |
          if [ -d "datasets" ]; then
            echo "Directory exists."
          else
            echo "Directory does not exist."
            exit 1
          fi